name: Build NestJS Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # o '20' si tu backend usa Node 20

      - name: Instalar dependencias
        run: npm install

      - name: Escaneo de dependencias con Snyk (agente SSA)
        uses: snyk/actions/node@v1
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Creación del build
        run: npm run build

      # - name: Ejecutar pruebas (opcional)
      #   run: npm run test

      # Guardar artefactos del build si lo deseas
      - name: Guardar artefactos compilados (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
